project_name: react
env:
    - GO111MODULE=on
    - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod vendor
builds:
    - binary: react
      main: .
      goos:
          - linux
          - darwin
          - windows
      goarch:
          - amd64
      env:
          - CGO_ENABLED=0

archives:
    - id: react
      format: zip
      files:
          - none

release:
    disable: true
