on:
  push:
    branches:
      - master
name: ReAcT
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Check for Tag
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: Check out code
      uses: actions/checkout@master
      if: success
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
      if: success
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go
    - name: Get dependencies
      run: |
        go mod vendor
    - name: Test
      run: go test -v ./...
