on: [push]
name: ReAcT
jobs:
  is-tag:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: is-tag
      uses: actions/bin/filter@master
      with:
        args: tag
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
      path: ${{ go.module-path }}
    - name: is-branch
      uses: actions/bin/filter@master
      with:
        args: not branch master
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go
    - name: Get dependencies
      working-directory: ${{ go.module-path }}
      run: |
        go mod vendor
    - name: Test 
      working-directory: ${{ go.module-path }}
      run: go test -v ./...
