#on: pull_request
on:
  push:
    paths:
      - '*/**'
    tags:
      - '!v*'
  workflow_dispatch:

name: ReAcT-testing
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint
      run: |
        make vet
        go get -u golang.org/x/lint/golint
        make lint
      if: success()

    - name: Test
      run: make test
      if: success()

    - name: Build
      run: go build -mod vendor ./...
      if: success()
