on:
  push:
    branches:
      - master
name: ReAcT-testing
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        version: 1.12
      id: go
    - name: Get dependencies
      run: |
        go mod vendor
      if: success()
    - name: Test
      run: go test -v ./...
      if: success()
    - name: Build
      run: go build -mod vendor ./...
      if: success()
